# Generated by Django 5.2.5 on 2025-09-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='titulo',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
