# Generated by Django 5.2.5 on 2025-09-02 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chamados', '0004_categoria_alter_setor_nome_chamado_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='setor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'URGENTE')], default='media', max_length=10),
        ),
        migrations.AddField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em Andamento'), ('aguardando', 'Aguardando Usuário'), ('resolvido', 'Resolvido'), ('fechado', 'Fechado')], default='aberto', max_length=15),
        ),
        migrations.DeleteModel(
            name='Setor',
        ),
    ]
