# Generated by Django 5.2.5 on 2025-09-02 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0005_alter_chamado_setor_id_chamado_prioridade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='foi_resolvido',
        ),
    ]
