# Generated by Django 5.2.5 on 2025-09-02 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0006_remove_chamado_foi_resolvido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chamado',
            old_name='setor_id',
            new_name='setor',
        ),
    ]
